import "../globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/modeToggle";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import LangSwitcher from "@/components/lang-switcher";
import { store } from "../../store/store";
import { Provider } from "react-redux";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <body className="bg-gradient-to-r from-gray-100 via-blue-50 to-gray-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900 text-gray-800 dark:text-gray-100 min-h-screen">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider>
            <div className="flex flex-col lg:flex-row min-h-screen">
              {/* Sidebar */}
              <AppSidebar className="w-full lg:w-64 bg-white dark:bg-gray-800 shadow-lg" />

              {/* Main Content */}
              <div className="flex-1 flex flex-col">
                {/* Top Bar */}
                <header className="flex items-center  justify-between p-4 bg-white dark:bg-gray-800 shadow-md">
                  <div className="flex items-center gap-4">
                    <SidebarTrigger />
                    <LangSwitcher locale={locale} />
                  </div>
                  <ModeToggle />
                </header>

                {/* Main Area */}
                <main>
                  <NextIntlClientProvider messages={messages}>
                    <Providers>{children}</Providers>
                  </NextIntlClientProvider>
                </main>
              </div>
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
